### ISSUE TITLE
Infinite loop in watch mode 

### ISSUE THREAD

**Issue by Liero** [michaelwayman/node-sass-chokidar#42]
I'm getting this output:

`npm run watch-css`

```
> my-app@0.1.0 watch-css C:\Project
> npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive


> my-app@0.1.0 build-css C:\Project
> node-sass-chokidar src/ -o src/

Rendering Complete, saving .css file...
Wrote CSS to C:\Project\src\index.css
Wrote 1 CSS files to C:\Project\src\
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
=> changed: C:\Project\src\index.scss
=> changed: C:\Project\node_modules\bootstrap\scss\bootstrap.scss
```

Here is my package json:

```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "bootstrap": "^4.0.0",
    "font-awesome": "^4.7.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts-ts": "2.13.0",
    "reactstrap": "^5.0.0-beta.2"
  },
  "scripts": {
    "build-css": "node-sass-chokidar src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch",
    "start-js": "react-scripts-ts start",
    "start": "npm-run-all -p watch-css start-js",
    "build-js": "react-scripts-ts build",
    "build": "npm-run-all build-css build-js",
    "test": "react-scripts-ts test --env=jsdom"
  },
  "devDependencies": {
    "@types/jest": "^22.1.3",
    "@types/node": "^9.4.6",
    "@types/react": "^16.0.38",
    "@types/react-dom": "^16.0.4",
    "@types/react-router-dom": "^4.2.4",
    "@types/reactstrap": "^5.0.18",
    "node-sass-chokidar": "^1.0.1",
    "npm-run-all": "^4.1.2",
    "typescript": "^2.7.2"
  }
}
```

and my index.scss:

```scss
$theme-colors: (
  "primary": #00ACD0,
  "warning": #FF6C0C
);
$btn-border-radius: 0;
$enable-shadows: true;

@import "node_modules/bootstrap/scss/bootstrap.scss";
```

**Comment by michaelwayman** [comment]
I'll try to look into this later today.
@Liero or @ronanmulvaney while I'm doing that, can you see if you get the same problem with `node-sass-chokidar==0.0.3` and report back?

**Comment by ervwalter** [comment]
I am seeing the same problems (many 'changed' notifications; CSS files being created in node_modules) after upgrading to 1.1.0.  I do not see it when I downgrade back to 0.0.3.

**Comment by gorkamolero** [comment]
Same thing happening to me, trying to import the Bulma framework

**Comment by maganuk** [comment]
Same here with bootstrap

**Comment by Liero** [comment]
@michaelwayman : I don't see the problem when I downgrade to node-sass-chokidar==0.0.3

**Comment by michaelwayman** [comment]
@maganuk @gorkamolero @ervwalter @ronanmulvaney @Liero 

Hey sorry about that guys, when fixing the issue of "files not being watched when first created" this bug was introduced, I didn't test `@import` while using `--watch` well enough.

I made a small adjustment and published it under `node-sass-chokidar: 1.1.1`
so basically, this should be fixed with the latest version of node-sass-chokidar.
I'm going to close this, let me know if you still see the problem after upgrading.

**Comment by vipyoshi** [comment]
Problem still occurring with version 1.1.2 for me

**Comment by erosenberg** [comment]
@michaelwayman - I'm still getting this error in the latest version 1.3.0. Looks like the build is failing too. I'm using Node 9. Could it be something to do with that?
